#!/usr/bin/env python

import subprocess
import os.path as op

_LPADMIN = '/usr/sbin/lpadmin'

NAME='__NAME__'
LOCATION='__LOCATION__'
PPD='__PPD__'
PPDIR='/Library/Printers/PPDs/Contents/Resources/'
PPD_FULL=PPDIR + PPD

if __name__ == '__main__':

    base_url = "smb://pushprint.uio.no/"
    url = base_url + NAME

    subprocess.check_call([_LPADMIN, "-p", NAME, "-L", LOCATION, "-v", url, "-P", PPD_FULL])
