#!/usr/bin/env python

import subprocess

_LPADMIN = '/usr/sbin/lpadmin'

NAME='test_printer'
LOCATION='LAB-1'
PPD=HP\ LaserJet\ 600\ M601\ M602\ M603.gz

if __name__ == '__main__':

    base_url = "smb://pushprint.uio.no/"
    url = base_url + NAME

    subprocess.check_call([_LPADMIN, "-p", NAME, "-L", LOCATION, "-v", url, "-P", PPD])
